# Site settings
title: Travis the Web Developer
header-img: img/home-bg.png
email: travywill@gmail.com
copyright_name: travywill
description: > # this means to ignore newlines until "baseurl:"
  Musings of an Aspiring Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  travywill
learn_profile: travywill
email_username: travywill@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
